#!/usr/bin/env bash
# A script to install and setup Nginx

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Verify Nginx is running
sudo service nginx status

# Create a test HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Reload Nginx
sudo kill -s HUP $(pidof nginx)
