#!/usr/bin/env bash

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Add configuration to Nginx
sudo sed -i '/server {/a location = /404.html { root /var/www/html; internal; } error_page 404 /404.html;' /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
