#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install -y haproxy=2.8.\*
echo "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
   balance roundrobin
   mode http
   server 340092-web-01 54.210.195.72:80 check
   server 340092-web-02 54.242.181.250:80 check" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
