#!/usr/bin/env bash
# fizzbuzz display
x=0
while [ $((x++)) -lt 100 ]; do
	if [ $((x % 15)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((x % 5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((x % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo $i
	fi
done
